name: firebase
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.2.6

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.6
  sqflite: ^2.3.3
  qr_code_scanner: ^1.0.1
  firebase_core: ^2.25.4
  firebase_auth: ^4.17.8
  firebase_database: ^10.4.9
  cloud_firestore: ^4.15.8
  qr_flutter: ^4.1.0 
  intl: ^0.19.0
  flutter_svg_provider: ^1.0.7
  cached_network_image: ^3.3.1
  flutter_email_sender: ^6.0.0
  url_launcher: ^6.2.6
  table_calendar: ^3.1.1
  flutter_qr_reader: ^1.0.5
  mobile_scanner: ^5.1.1
  image_picker: ^1.1.1
  path_provider: ^2.0.11
  fl_chart: ^0.68.0
  vibration: ^1.9.0
  flutter_sound: ^9.2.13
  cloud_functions: ^4.7.6
  interactive_canvas: ^0.0.2
  mailer: ^6.1.0
  uni_links: ^0.5.1
  pdf: ^3.10.8
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0


flutter: 
  uses-material-design: true
  assets: 
    - assets/
    - assets/images/
  fonts: 
    - family: Montserrat
      fonts: 
        - asset: assets/fonts/MontserratRomanMedium.ttf
          weight: 500
        - asset: assets/fonts/MontserratRomanSemiBold.ttf
          weight: 600
        - asset: assets/fonts/MontserratRomanRegular.ttf
          weight: 400
    - family: Inter
      fonts: 
        - asset: assets/fonts/InterBold.ttf
          weight: 700
        - asset: assets/fonts/InterMedium.ttf
          weight: 500
        - asset: assets/fonts/InterRegular.ttf
          weight: 400
    - family: Gowun Dodum
      fonts: 
        - asset: assets/fonts/GowunDodumRegular.ttf
          weight: 400